fix build on CentOS7
Before this patch an attempt to build on CentOS 7 (gcc 4.8.5)
failed with error:
```
[ 63%] Building C object src/CMakeFiles/merger.dir/compat/utils.c.o
[ 72%] Building C object src/CMakeFiles/merger.dir/merger/merger.c.o
/tmp/luarocks_tuple-merger-0.0.1-1-Cwe2jE/tuple-merger/src/merger/merger.c: In function 'luaT_merger_new_parse_sources':
/tmp/luarocks_tuple-merger-0.0.1-1-Cwe2jE/tuple-merger/src/merger/merger.c:306:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (uint32_t i = 0; i < source_count; ++i) {
  ^
/tmp/luarocks_tuple-merger-0.0.1-1-Cwe2jE/tuple-merger/src/merger/merger.c:306:2: note: use option -std=c99 or -std=gnu99 to compile your code
gmake[5]: *** [src/CMakeFiles/merger.dir/merger/merger.c.o] Error 1
```

However we can't simply enable c99 mode because "typeof" is gcc
extension and otherwise it failed with:
```
/opt/tarantool/tuple-merger/src/merger/merger.c:917:54: error: unused parameter ‘base’ [-Werror=unused-parameter]
 luaL_merge_source_tuple_destroy(struct merge_source *base)
                                                      ^
In file included from /opt/tarantool/tuple-merger/src/merger/merger.c:44:0:
/opt/tarantool/tuple-merger/src/merger/merger.c: In function ‘luaL_merge_source_tuple_next_impl’:
/usr/local/include/tarantool/module.h:201:16: error: expected declaration specifiers or ‘...’ before (’ token
  const typeof( ((type *)0)->member  ) *__mptr = (ptr); \
                ^
/opt/tarantool/tuple-merger/src/merger/merger.c:937:38: note: in expansion of macro ‘container_of’
  struct merge_source_tuple *source = container_of(base,
```

So, finally after enable gnu99 mode all seems to be ok.

Closes #19